parameters:
  # Default db info
  app.secret.database.schema:   'application'
  app.secret.database.host:     'localhost'
  app.secret.database.username: 'user'
  app.secret.database.password: 'pass'

  # Common config database
  app.database.common:
    dsn: 'mysql:dbname=%app.secret.database.schema%;host=%app.secret.database.host%;charset=UTF8'
    username: '%app.secret.database.username%'
    password: '%app.secret.database.password%'
    options:
      !php/const \PDO::MYSQL_ATTR_INIT_COMMAND: "SET NAMES 'UTF8'"

services:
  _defaults:
    autoconfigure: true

  Eureka\Component\Database\ConnectionFactory:
    arguments:
      $configs:
        common: '%app.database.common%'
