parameters:

  meta.config:
    title: 'France Stats'
    charset: 'utf-8'

    app:
      name_short: ''
      name_full: 'France Stats'

    description: 'France Stats web application'
    keywords:    'France, web, application, statistiques'
    author:      'Romain Cottard'
    version:     '%app.version%'

    copyright:
      year: 'now'
      name: 'velkuns'

    footer:
      links: [ ]

    #~ Other meta data

    social:
      facebook: '#'
      twitter: 'https://twitter.com/velkuns'
      feed: '#'
