parameters:

  app.middleware:
    timeLogger:     'Eureka\Kernel\Http\Middleware\ResponseTimeLoggerMiddleware'
    errorWeb:       'Eureka\Kernel\Http\Middleware\ErrorMiddleware'
    twig:           'Application\Middleware\TwigMiddleware'
    router:         'Eureka\Kernel\Http\Middleware\RouterMiddleware'
    rateLimiter:    'Eureka\Kernel\Http\Middleware\RateLimiterMiddleware'
    controller:     'Eureka\Kernel\Http\Middleware\ControllerMiddleware'

services:
  _defaults:
    autowire: true
    public:   true
    bind:
      $applicationName: '%app.name%'
      $cache:           '@app.cache.default'

  #~ Global Kernel Services Middleware
  Eureka\Kernel\Http\Middleware\:
    resource: '../../vendor/eureka/kernel-http/src/Middleware'

  #~ Global Application Services Middleware
  Application\Middleware\:
    resource: '../../src/Middleware'

  #~ Error middleware for classic web application
  Eureka\Kernel\Http\Middleware\ErrorMiddleware:
    arguments:
      $errorController: '@Application\Controller\Web\Error\ErrorController'
