parameters:

  #~ Comment part
  orm.comment.author:    'Eureka Orm Generator'
  orm.comment.copyright: 'Romain Cottard'

  #~ Namespace base config
  orm.base_namespace.entity:     'Application\Domain'
  orm.base_namespace.mapper:     'Application\Domain'
  orm.base_namespace.repository: 'Application\Domain'

  #~ Path base config
  orm.base_path.entity:     '%kernel.directory.root%/src/Domain'
  orm.base_path.mapper:     '%kernel.directory.root%/src/Domain'
  orm.base_path.repository: '%kernel.directory.root%/src/Domain'

  #~ Cache base config
  orm.cache.enabled: false
  orm.cache.prefix:  'application.'

  #~ Validation
  orm.validation.enabled: true
  orm.validation.auto:    true

  #~ Subdomain config
  orm.config.subdomain.common: 'Common'

  #~ Configs
  orm.configs:
    unemployment:       '%orm.config.unemployment%'
    unemployment_value: '%orm.config.unemployment_value%'

services:
  _defaults:
    autowire: true
    bind:
      $connectionName: 'common'

  ######################################################################################################################
  # COMMON
  ######################################################################################################################
  Eureka\Component\Orm\:
    resource: '../../vendor/eureka/component-orm/src/*'

  Eureka\Component\Validation\:
    resource: '../../vendor/eureka/component-validation/src/*'

  ######################################################################################################################
  # SCRIPTS
  ######################################################################################################################
  Eureka\Component\Orm\Script\Generator:
    public: true
    arguments:
      $ormConfigs: '%orm.configs%'

  ######################################################################################################################
  # MAPPERS
  ######################################################################################################################
  Application\Domain\Unemployment\:
    resource: './../../src/Domain/Unemployment/*'
    exclude:  './../../src/Domain/Unemployment/{Entity}'

  Application\Domain\Unemployment\Infrastructure\Mapper\UnemploymentMapper:
    arguments:
      $mappers:
        'Application\Domain\Unemployment\Infrastructure\Mapper\UnemploymentValueMapper': '@Application\Domain\Unemployment\Infrastructure\Mapper\UnemploymentValueMapper'
