services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true

  router:
    public: true
    alias: Symfony\Component\Routing\Router

  Symfony\Component\Routing\:
    resource: '../../vendor/symfony/routing/*'
    exclude:  '../../vendor/symfony/routing/{Router,Tests}'

  Symfony\Component\Config\:
    resource: '../../vendor/symfony/config/*'
    exclude:  '../../vendor/symfony/config/{FileLocator,Tests}'

  Symfony\Component\Config\Loader\LoaderInterface:
    alias: Symfony\Component\Routing\Loader\YamlFileLoader

  Symfony\Component\Config\FileLocatorInterface:
    alias: Symfony\Component\Config\FileLocator

  Symfony\Component\Config\FileLocator:
    arguments:
      - '%kernel.directory.config%'

  Symfony\Component\Routing\Router:
    arguments:
      $loader:   '@Symfony\Component\Routing\Loader\YamlFileLoader'
      $resource: '%kernel.directory.config%/routes/routes.yaml'
      $options:
        cache_dir: '%kernel.directory.cache%/%kernel.environment%'
        debug: true
