# For route with log-in needed, add following parameter in defaults: "authenticationRequired: true"
# ======================================================================================================================
# =                                                 WEB                                                                =
# ======================================================================================================================
home:
    path:       /
    controller: Application\Controller\Web\Home\HomeController::index
    methods:    [GET]
    defaults:
        authenticationRequired: false


# ======================================================================================================================
# =                                                 WEB                                                                =
# ======================================================================================================================
api_ping:
    path:       /api/ping
    controller: Application\Controller\Api\Home\HomeApiController::ping
    methods:    [GET]
    defaults:
        authenticationRequired: false
